discord:
  webhook: "PUT_WEBHOOK_URL_HERE"

privacy:
  mask-ips: false # If true, last two octets of IPs will be replaced with x (e.g. 192.168.xx.xx)

messages:
  blocked: "&cLogin blocked: IP mismatch.If you believe this is a mistake contact the owner"
